# Ch 5. Resampling

### Imports

In [21]:
import numpy as np
import statsmodels.api as sm
from ISLP import load_data
from ISLP.models import (
    ModelSpec as MS,
    summarize,
    poly,
    sklearn_sm
)
from sklearn.model_selection import (
    train_test_split,
    cross_validate,
    KFold,
    ShuffleSplit
)
from sklearn.base import clone

### Functions to Use

In [38]:
def evalMSE(terms, response, train, test):
    mm = MS(terms)
    
    # Fit the model using the training data
    X_train = mm.fit_transform(train)
    y_train = train[response]
    
    # Transform the test data without fitting the model again
    X_test = mm.transform(test)  # Use transform instead of fit_transform
    y_test = test[response]  # This should likely reference 'test' instead of 'train'
    
    results = sm.OLS(y_train, X_train).fit()
    test_pred = results.predict(X_test)
    
    return np.mean(
        (y_test - test_pred) ** 2    
    )

### Load Data

In [23]:
Auto = load_data("Auto")
Auto_train, Auto_dev = train_test_split(
    Auto,
    test_size=196,
    random_state=0
)

### Fit Linear Regression

In [24]:
# specify model?
hp_mm = MS(['horsepower'])
X_train = hp_mm.fit_transform(Auto_train)
y_train = Auto_train['mpg']
model = sm.OLS(y_train,X_train)
results = model.fit()

In [31]:
X_dev = hp_mm.fit_transform(Auto_dev)
y_dev = Auto_dev['mpg']
dev_pred = results.predict(X_dev)
np.mean(
    (y_dev - dev_pred) **2
)

23.61661706966987

### Use custom function to estimate dev MSE using different power fits.

In [49]:
MSE = np.zeros(3)
for idx, degree in enumerate(range(1, 4)):
    MSE[idx] = evalMSE(
      [poly('horsepower', degree)],
        'mpg',
        Auto_train ,
        Auto_dev
    )
MSE

array([23.61661707, 18.76303135, 18.79694163])

### Perform LOOCV looking at error

In [45]:
hp_model = sklearn_sm(
    sm.OLS,
    MS(['horsepower'])
)

X, y = Auto.drop(columns = ['mpg']), Auto['mpg']

cv_results = cross_validate(
    hp_model,
    X,
    y,
    cv = Auto.shape[0]
)

cv_err = np.mean(cv_results['test_score'])
cv_err

24.231513517929233

### Do the same process but across different polynomiels

In [47]:
cv_error = np.zeros(5)
H = np.array(Auto['horsepower'])
M = sklearn_sm(sm.OLS)
for i, d in enumerate(range(1,6)):
    X = np.power.outer(H, np.arange(d+1))
    M_CV = cross_validate(
        M,
        X,
        y,
        cv = Auto.shape[0]
    )
    cv_error[i] = np.mean(M_CV['test_score'])
cv_error

array([24.23151352, 19.24821312, 19.33498406, 19.42443032, 19.03323636])

In [51]:
cv_error = np.zeros(5)
cv = KFold(
    n_splits=10,
    shuffle=True,
    random_state=0
) 
# use same splits for each degree

for i, d in enumerate(range(1,6)):
    X = np.power.outer(H, np.arange(d+1))
    M_CV = cross_validate(
        M,
        X,
        y,
        cv=cv
    )
    cv_error[i] = np.mean(M_CV['test_score'])
cv_error

array([24.20766449, 19.18533142, 19.27626666, 19.47848402, 19.13719339])

In [52]:
validation = ShuffleSplit(
    n_splits=1,
    test_size=196,
    random_state=0
)

results = cross_validate(
    hp_model,
    Auto.drop(['mpg'],axis=1),
    Auto['mpg'],
    cv = validation
)

results['test_score']

array([23.61661707])

### test variability in ^^^

In [53]:
validation = ShuffleSplit(
    n_splits=10,
    test_size=196,
    random_state=0
)

results = cross_validate(
    hp_model,
    Auto.drop(['mpg'],axis=1),
    Auto['mpg'],
    cv = validation
)

results['test_score'].mean(), results['test_score'].std()

(23.80223266103416, 1.4218450941091862)

# Bootstrap

### Load Data

In [54]:
Portfolio = load_data('Portfolio')

### Simple Function

In [55]:
def alpha_func(Dataframe, idx):
    cov_ = np.cov(
        Dataframe[['X','Y']].loc[idx],
        rowvar = False
    )
    
    return (
        (cov_[1,1] - cov_[0,1]) / (cov_[0,0] + cov_[1,1] -2*cov_[0,1])
    )

In [56]:
 alpha_func(Portfolio , range(100))

0.5758320745928298

In [57]:
rng = np.random.default_rng(0)
alpha_func(
    Portfolio,
    rng.choice(
        100,
        100,
        replace = True
    )
)

0.6074452469619002

### Compound Function

In [58]:
def boot_SE(func, D, n = None, B = 1000, seed = 0):
    
    rng = np.random.default_rng(seed),
    first_, second_ = 0,0
    n = n or D.shape[0]
    
    for _ in range(B):
        idx = rng.choice(
            n,
            replace = True
        )
        
        value = func(D, idx)
        first_ += value
        second += value ** 2
    return np.sqrt(
        second_ / B - (first_ / B) ** 2
    )

In [65]:
def boot_SE(func, D, n=None, B=1000, seed=0): 
    rng = np.random.default_rng(seed) 
    first_ , second_ = 0, 0 
    n = n or D.shape[0] 
    for _ in range(B): 
        idx = rng.choice(D.index , 
                         n, 
                         replace=True) 
        value = func(D, idx) 
        first_ += value 
        second_ += value**2 
    return np.sqrt(second_ / B - (first_ / B)**2)

In [68]:
alpha_SE = boot_SE(
    alpha_func ,             
    Portfolio ,              
    B=1000,            
    seed=0
)

alpha_SE

0.09118176521277577

In [69]:
def boot_OLS(model_matrix , response , D, idx):
    D_ = D.loc[idx]
    Y_ = D_[response]
    X_ = clone(model_matrix).fit_transform(D_)
    return sm.OLS(Y_, X_).fit().params

In [72]:
from functools import partial

In [73]:
hp_func = partial(boot_OLS , MS(['horsepower']), 'mpg')

In [75]:
rng = np.random.default_rng(0)
np.array(
    [
        hp_func(
            Auto,
            rng.choice(392,392, replace=True)) for _ in range(10)
    ]
)

array([[39.88064456, -0.1567849 ],
       [38.73298691, -0.14699495],
       [38.31734657, -0.14442683],
       [39.91446826, -0.15782234],
       [39.43349349, -0.15072702],
       [40.36629857, -0.15912217],
       [39.62334517, -0.15449117],
       [39.0580588 , -0.14952908],
       [38.66688437, -0.14521037],
       [39.64280792, -0.15555698]])

In [77]:
hp_se = boot_SE(
    hp_func,
    Auto,
    B=1000,
    seed=10
)
hp_se

intercept     0.848807
horsepower    0.007352
dtype: float64

In [78]:
hp_model.fit(Auto, Auto['mpg'])
model_se = summarize(hp_model.results_)['std err']
model_se

intercept     0.717
horsepower    0.006
Name: std err, dtype: float64

In [79]:
quad_model = MS([poly('horsepower', 2, raw=True)])
quad_func = partial(
    boot_OLS ,
    quad_model ,
    'mpg'
)
boot_SE(quad_func , Auto, B=1000)

intercept                                  2.067840
poly(horsepower, degree=2, raw=True)[0]    0.033019
poly(horsepower, degree=2, raw=True)[1]    0.000120
dtype: float64

In [80]:
M = sm.OLS(Auto['mpg'],
quad_model.fit_transform(Auto))
summarize(M.fit())['std err']

intercept                                  1.800
poly(horsepower, degree=2, raw=True)[0]    0.031
poly(horsepower, degree=2, raw=True)[1]    0.000
Name: std err, dtype: float64